package by.peekhovsky.restview.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;


/**
 * @author Rostislav Pekhovsky 2018
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "user", schema = "public")
public class User {

    /**
     * User id in database.
     * It is autogenerated value.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Login name.
     */
    private String login;
    /**
     * Codified password.
     */
    private String hashPassword;
    /**
     * A first name.
     */
    private String firstName;
    /**
     * Last name.
     */
    private String lastName;
}